### PR TITLE
Roadmap changes

### PR DESCRIPTION
**Pull request by jodb**

### CODE REVIEW

**Comment by jodb** [comment]
When reviewing, two things to keep in mind

- When you go from the `Learn` page to `Blog`, currently blog does not have a left menu bar https://deploy-preview-31--delta-io-beta.netlify.app/learn
- The new style I gave to the tables on the roadmap page also are on the table on the community page https://deploy-preview-31--delta-io-beta.netlify.app/community

**Comment by dennyglee** [comment]
- Roadmap looks great. 
- Learn menu with the "Blog" in left-hand looks great
- Please add latest blogs similar tutorials or videos

**Comment by jodb** [comment]
@dennyglee I think this is ready for a review. I added a latest blog section to the learn page. I'm not sure why but the netlify build process doesn't seem to be running to update the PRs preview with my latest changes.

**Review by dennyglee — APPROVED** [review]
LGTM

**Pull request merged**
