### PR TITLE
Add Delta Sharing 0.5.0 Released Blog

### PR DESCRIPTION
**Pull request by goodwillpunning**
This commit adds a new blog article for announcing the release of Delta Sharing 0.5.0.

### CODE REVIEW

**Comment by dennyglee** [comment]
Blog looks great, could you also update the front page under "latest" section to include your post as well?  Thanks!

**Comment by goodwillpunning** [comment]
Good catch! Updated. Thanks!

**Comment by goodwillpunning** [comment]
I love it! Great suggestion. Keeps things interesting. The latest commit updates the blog title 👍

**Review by dennyglee — APPROVED** [review]
Awesome!!

**Pull request merged**
