### PR TITLE
[Blog] Add Daft + Delta Lake blog post.

### PR DESCRIPTION
**Pull request by clarkzinzow**
This PR adds a blog post for distributed + parallel reading of large Delta Lake tables with Daft.

### CODE REVIEW

**Comment by clarkzinzow** [comment]
cc @dennyglee

**Comment by clarkzinzow** [comment]
@dennyglee Indeed, I'll work on fixing the spacing for some of the images!

**Comment by clarkzinzow** [comment]
@dennyglee I've fixed the spacing in the images and updated some of the copy. It appears that the docs preview build doesn't automatically trigger on new commits, do we need to do anything to trigger another build?

**Comment by dennyglee** [comment]
This is looking great @clarkzinzow.  super minor nit, so feel free to disregard - perhaps have the splash screen of your blog on the front screen be this [image](https://deploy-preview-390--delta-io-beta.netlify.app/static/3515c03f66eb3f3aaa28c204f7cbd200/0a47e/json_speedup.png)?    It's the right size (and matches the other splash screens) and its really compelling, eh?!

**Comment by clarkzinzow** [comment]
@dennyglee Updated with a new thumbnail and a top-of-page landing image that we're thinking about adding, could you kick off another build?

**Review by dennyglee — APPROVED** [review]
LGTM!

**Comment by dennyglee** [comment]
Kicked off and approved!  Please do a quick sanity check and I’ll merge.
Thanks !

**Comment by clarkzinzow** [comment]
@dennyglee M=Just made some final tweaks to the benchmarking setup info formatting, good to merge when you are!

**Review by dennyglee — APPROVED** [review]

**Comment by dennyglee** [comment]
Love it @clarkzinzow - merging now!

**Pull request merged**
