### PR TITLE
adding in StarRocks entry to integrations page

### PR DESCRIPTION
**Pull request by alberttwong**
Adding in StarRocks, a database that can read delta lake. Database was mentioned at the DataBricks keynote this year. https://www.youtube.com/watch?v=CU8krhcNI2M&t=88s

### CODE REVIEW

**Review by dennyglee — CHANGES_REQUESTED** [review]
@alberttwong By any chance can you include a logo of StarRocks just with the icon?  It'll look much bigger on the page as right now, your logo looks smaller than the other logos

**Comment by alberttwong** [comment]
dark_logo

I don't mind a smaller logo that others.  I'd rather keep the logo with the words because we are not well known yet.

**Comment by dennyglee** [comment]
@alberttwong note, the name "StarRocks" will be immediately under your logo so it will be seen. I can merge as is but from an esthetic point of view so folks can see your logo, would suggest only having the icon.

**Comment by alberttwong** [comment]
@dennyglee I made the changes but it seems like it's stuck on the build.

**Comment by dennyglee** [comment]
Sorry about that, the build is fixed now.  @alberttwong - please check https://deploy-preview-332--delta-io-beta.netlify.app/integrations and let me know if this works?  If so, I'll approve, and merge - thanks!

**Comment by alberttwong** [comment]
Looks good

**Review by dennyglee — APPROVED** [review]
LGTM!

**Pull request merged**
