### PR TITLE
#141 - adding the contributing to delta page

### PR DESCRIPTION
**Pull request by sibyabin**
Signed-off-by: sibyabin <sibyoncloud@gmail.com>

- Added ``` src/pages/resources/contributing-to-delta.mdx ```
- Updated ```delta-io/delta/blob/master/CONTRIBUTING.md``` to ```contributing-to-delta```

### CODE REVIEW

**Comment by dennyglee** [comment]
Thanks very much for your contribution @sibyabin - will review shortly!

**Comment by dennyglee** [comment]
This looks great @sibyabin - quick question, do you think we could add a breadcrumb at the top so folks can traverse back to the community page?  WDYT?

**Comment by sibyabin** [comment]
Hi @dennyglee , Do you mean a breadcrumb only for this page?

We have any way "community" menu on the top of every page ,  got the same in the footer as well and of course you have a back button on browser as the last option ;)

do you think this can be applicable to all the child pages of the site ? Lets not close this PR , I'll try to see if I can do something over the weekend and will come back  on this.

**Comment by dennyglee** [comment]
I’m thinking that we may want to start doing bread crumbs and navigation side bars as more information gets added to the site.  We do have some examples of left-hand navigation but thinking if its a single page, it may be cleaner to do a bread crumb and have that applicable to other pages as we add them, eh?!  WDYT?

**Review by dennyglee — APPROVED** [review]
LGTM!

**Comment by dennyglee** [comment]
Thanks @sibyabin for this PR!

**Comment by sibyabin** [comment]
closes #141

**Pull request merged**
