### PR TITLE
4 added fixes and new features

### PR DESCRIPTION
**Pull request by dev-smart-ui**
Hey folks! Here the next updates: 

1) Added form as html file. You can see it on the url “/form.html”. You can add query params (as I see, the offer_code) and use it. It works. 

2) Changed the “Contributor of the month” section and added Gerhard’s profile. Changed a list so you would link to the personal profile. 

3) I created my own Youtube channel to test the error of the building process when you created the scheduled video. I created a lot of scheduled videos in different variations but I didn't catch errors. So, please let me know when you catch errors with your building process and I would explore it. 

4) Added aligning the thumbnails, added the logos for the sections. 

5) Added the script for Hubspot chat. As I know you need to set up the chat through your personal profile on Hubspot. Chat is working, I tested it on my own Hubspot profile.

6) Remove duplicate videos on the community page.

PS. Sorry, sometimes I see someone from your team tries to add updates to our fork of your repository. This is a bad idea because all these changes will not show up on your site. And before I start working, I need to synchronize this fork with your repository and I need to cancel all other commits in our fork. That's how it works.

### CODE REVIEW

**Comment by dev-smart-ui** [comment]
Extra vertical spacing between "Watch the latest videos and webinars for the open-source Delta Lake project." and "Last Week in a Byte"
....
Sorry, could you clarify we need to add or remove extra spacing?

**Comment by dennyglee** [comment]
Oh sorry, hope this image helps clarifies everything in terms of a header and vertical spacing.  thanks!
Screenshot 2023-02-21 at 12 23 49 PM

**Comment by dev-smart-ui** [comment]
Thanks for appreciating our work! Here the next addition:
1. Removed the logo from the front of the page.
2. I have used the correct logo to the pages. 
3. Added extra vertical spacing between the videos list collection.
4. Increased the title size of the videos collection list. 
....
Let us know if everything is good. 
Thanks!

**Review by dennyglee — APPROVED** [review]
This looks amazing - thanks!

**Pull request merged**
