### PR TITLE
Community + Roadmap section updates

### PR DESCRIPTION
**Pull request by dennyglee**
Due to a previous caching issue, we had to temporarily rename the community page to community-page.  This update fixes the following: 
- renames the community-page.jsx back to community.jsx
- renames the community folder to resources folder
- renames the resources/index.jsx to index.txt (will delete this at a later time)
- updates the roadmap links to point to go.delta.io/roadmap so whenever we make changes to the roadmap link, it will go to the same location.

### CODE REVIEW

**Comment by MrPowers** [comment]
LGTM, but someone that's more familiar with Neltify should give the approval

**Comment by dennyglee** [comment]
> LGTM, but someone that's more familiar with Neltify should give the approval

Actually, it's all good for you to approve. Netlify just hosts the code-base (and provides the awesome infrastructure).  If it works on the preview per https://deploy-preview-121--delta-io-beta.netlify.app/ - then please approve.  Thanks!

**Review by MrPowers — APPROVED** [review]
Demo site is working as expected, thanks!

**Comment by dennyglee** [comment]
Much appreciated!

**Pull request merged**
