### PR TITLE
updated whitepapers section

### LINKED ISSUE #230: Update whitepapers section on homepage
Here's the current whitepapers section:

Screen Shot 2023-02-05 at 10 42 43 AM

We should update this to link to both whitepapers:

* [Analyzing and comparing Lakehouse storage systems](https://www.cidrdb.org/cidr2023/papers/p92-jain.pdf)
* [Lakehouse architecture: Unifying data warehouses and advanced analytids](https://www.cidrdb.org/cidr2021/papers/cidr2021_paper17.pdf)

### PR DESCRIPTION
**Pull request by dev-smart-ui**
resolves #230

### CODE REVIEW

**Comment by dennyglee** [comment]
Note, for the whitepapers, suggest that:
- update the top text to say "Read the Lakehouse Storage Systems Whitepapers"
- update the description text to "These whitepapers dive into the features of Lakehouse storage systems and compare Delta Lake, Apache Hudi, and Apache Iceberg. They also explain the benefits of Lakehouse storage systems and show key performance benchmarks."
- update the left link to say "Analyzing and Comparing Lakehouse Storage Systems"
- update the left graphic to be a screenshot of Figure 1 of the paper, including the caption
- update the right link to say "Lakehouse: A New Generation of Open Platforms that Unify
Data Warehousing and Advanced Analytics"
- update the right graphic to be a screenshot of Figure 2 of the paper including the caption
- at the bottom of the graphic, please add a text link to the paper [Delta lake: high-performance ACID table storage over cloud object stores](https://dl.acm.org/doi/10.14778/3415478.3415560)

**Comment by dennyglee** [comment]
Thanks @dev-smart-ui  - one small nit, could we make the bottom text from "[Delta lake: high-performance ACID table storage over cloud object stores](https://dl.acm.org/doi/10.14778/3415478.3415560)" to "[Delta Lake: high-performance ACID table storage over cloud object stores](https://dl.acm.org/doi/10.14778/3415478.3415560)" and put the text in a blue button similar to the "Read the whitepaper"?  Otherwise, looks great!

**Comment by MrPowers** [comment]
@dev-smart-ui - can you please make the change Denny requested?  Let me know when this is done - thanks!!

**Review by dennyglee — APPROVED** [review]
LGTM!

**Pull request merged**
